# Generated by Django 5.0.1 on 2024-02-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('fsubject', models.CharField(max_length=30)),
                ('fquery', models.TextField()),
                ('fphone', models.IntegerField()),
            ],
        ),
    ]
